services:
  relink:
    ports:
      - '8080:8080'
    build: .
    depends_on:
      - relink-db
    entrypoint: sh -c 'until nc -z relink-db 5432; do echo "Waiting for database..."; sleep 1; done && exec /app/relink'


  relink-db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - relink-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  relink-data:
